### ISSUE TITLE
OMG!!! this is epic, how do I define the root as my entire vault

### ISSUE THREAD

**Issue by zeltak** [levirs565/obsidian-dendron-tree#1]
OMG OMG, been waiting for such a plug in for ages!!

thank so much for taking the time to implement this :)

I can define as a root any subfolder in my vault but how does one define my entire vault as root, it gives me an error it dosent exist

here is my vault structure

![CleanShot 2023-05-20 at 17 10 58](https://github.com/levirs565/obsidian-dendron-tree/assets/498410/f46c114a-eeb0-4718-bed3-5c44fe260cf5)

thx so much for making my weekend!

Z

**Comment by levirs565** [comment]
Are dendron icon in ribbon bar exist?

**Comment by zeltak** [comment]
yes it does. and I can add a specific folder , ie define my `tech` folder and it works!

![CleanShot 2023-05-21 at 09 04 50](https://github.com/levirs565/obsidian-dendron-tree/assets/498410/e90ee706-bc19-463a-9017-384b1c893872)


but how does one define the root level as the vault ie

![CleanShot 2023-05-21 at 09 05 22](https://github.com/levirs565/obsidian-dendron-tree/assets/498410/47e8e84a-89df-42b4-a0c6-68c1f9c153cd)


thx so much again

Z

**Comment by levirs565** [comment]
You can set "Vault Path" in "Dendron Tree Settings" to blank string in order to set vault directory to obsidian root directory.  However, if you do that, notes in subdirectory are not added into tree. This behaviour is also occurred in Dendron Visual Studio Code plugin.

To solve this issue we can add all subdirectory as vault. However, currently this plugin does not support multivault. I will implement this feature soon when i have free time.

**Comment by levirs565** [comment]
Newer version of Dendron Tree is released. This release bring support for multi vault. I hope this will fix this issue.

**Comment by zeltak** [comment]
amazing! works like a charm :)

thx so much for your epic work!

Z
